[package]
name = "armageddon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = {version= "=0.10.0", features = ["image"]}
rand = {version="0.8.5"}
